### ISSUE TITLE
Requesting Time Off: User cannot edit time off request

### ISSUE THREAD

**Issue by jack-reed** [testdrivensolutions/erp-system#446]
**Describe the bug**
Editing time off request fails consistently, also breaks the ui so they cannot interact with it going forward

**To Reproduce**
1. Go to 'Time off' page
2. Create new time off request
3. Edit request

**Comment by nrsleonardo** [comment]
great catch @jack-reed !!
I pushed the fix for the incremental scenario and changed the step to .25 instead of .5 for more control

**Comment by jack-reed** [comment]
Thanks for sorting that @nrsleonardo, I do have some queries on how weekends can be included in the date selection tool,  but we can discuss today at some point. Aside from that this is good to merge!
